//Author : Nemuel Wainaina

/*This is a simple game in which the computer generates a random number
 *and the user attempts to guess the generated number
 *If the user's guess is less than the correct number, the computer tells the user that their guess is too low,
 *If the user's guess is greater than the correct number, the program tells the user that their guess is too high
 *else the user's guess is correct and hurray !!! Haha ... !
 *The user can then choose on whether they want to have another round of the game,
 *If so, well and good, they get to play the game again :)
 *else, the game ends and the program terminates :(

 *HAVE FUN !!!
*/

#include<iostream>
#include<cstdlib>
#include<ctime>

using namespace std;

//This is the function that well, prints out some welcome text into the game on the screen for the user
void welcome(){
    cout<<"================================================================="<<endl;
    cout<<"                        Guess A Number Game                      "<<endl;
    cout<<"================================================================="<<endl;
    cout<<"                        #Nemuel Wainaina                         "<<endl;
    cout<<"-----------------------------------------------------------------"<<endl;
}
//This is the function that generates the random number and returns it to the caller
int random_num(int high ){
    srand((unsigned) time (NULL));
    int rnd = rand() % high + 1;
    return rnd;
}

int main(){
    char ch = 'y';
    int x;
    welcome();
    do{

        system("cls");
        welcome();

        cout<<"You are to guess a number between 1 and the number x eg 10 ... \n";
        cout<<"Enter the value of x first : ";
        cin>>x;

        int num, user_guess;
        int failed_attempts;
        num = random_num(x);

        trytoguess:
        cout<<"\nI have a random number between 1 and "<<x<<". What is the number ? ";
        cin>>user_guess;
        while(user_guess != num){
            failed_attempts++; // we increment the number of failed attempts by 1
            if(user_guess<1 || user_guess>x){
                cout<<"\tYour guess is out of range!"<<endl;
                cout<<"\tAllowed values are in the range : "<<1<<"-"<<x<<endl;
            }
            else if(user_guess>num){
                cout<<"\tYour guess is too high!"<<endl;
            }
            else{
                cout<<"\tYour guess is too low!"<<endl;
            }

            //system("cls"); ->The reason I have had to oomment out this section is so that I could have some time to see
            //whether my guess is too high or low as compared to the actual random number that is generated by the program
            goto trytoguess; //But don't use labels, not really recommended, haha !
        }
        cout<<"\tCongratulations !!!\n"<<"\tThe number is : "<<num<<endl;
        cout<<"\tNumber of Failed Attempts is : "<<failed_attempts<<endl<<endl;

        cout<<"Would you like to give it another try ? ['y', 'n'] : ";
        cin>>ch;
        cout<<endl;


    }while(ch == 'y' || ch == 'Y');

    system("cls");
    welcome();
    cout<<"Goodbye !\n"<<"Hope you enjoyed the game !"<<endl;

    return 0;
}
